# Generated by Django 6.0 on 2025-12-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_person',
            field=models.CharField(blank=True, help_text='Person money is going to or coming from', max_length=100, null=True),
        ),
    ]
